# Generated by Django 5.2.7 on 2026-08-13 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_simpeg', '0003_add_pas_foto_pegawai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdpAsn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_dari', models.DateField(help_text='Tanggal awal periode IDP', verbose_name='Periode IDP (Dari)')),
                ('periode_sampai', models.DateField(help_text='Tanggal akhir periode IDP', verbose_name='Periode IDP (Sampai)')),
                ('target_penugasan_idp', models.TextField(blank=True, default='', help_text='Target penugasan yang ingin dicapai pada periode ini', verbose_name='Target Penugasan IDP')),
                ('dasar_penyusunan_idp', models.TextField(blank=True, default='', help_text='Dasar/acuan dalam penyusunan IDP', verbose_name='Dasar Penyusunan IDP')),
                ('target_kompetensi', models.TextField(blank=True, default='', help_text='Target kompetensi yang ingin dikembangkan', verbose_name='Target Kompetensi')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='draft', help_text='Status IDP', max_length=20, verbose_name='Status')),
                ('catatan', models.TextField(blank=True, default='', help_text='Catatan tambahan atau alasan penolakan', verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tanggal Diupdate')),
                ('asn', models.ForeignKey(help_text='ASN yang menjadi subjek IDP', on_delete=django.db.models.deletion.PROTECT, related_name='idp_asn', to='api_simpeg.pegawai', verbose_name='ASN')),
                ('atasan_langsung', models.ForeignKey(blank=True, help_text='Atasan langsung dari ASN yang bersangkutan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idp_atasan', to='api_simpeg.pegawai', verbose_name='Atasan Langsung')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idp_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'IDP ASN',
                'verbose_name_plural': 'IDP ASN',
                'db_table': 'idp_asn',
                'ordering': ['-created_at'],
            },
        ),
    ]
