# Generated by Django 5.2.7 on 2026-08-13 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idpasn',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Waktu IDP disetujui atau ditolak', null=True, verbose_name='Waktu Persetujuan'),
        ),
        migrations.AddField(
            model_name='idpasn',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User yang melakukan persetujuan atau penolakan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idp_approved', to=settings.AUTH_USER_MODEL, verbose_name='Disetujui/Ditolak Oleh'),
        ),
    ]
