# Generated by Django 4.2 on 2026-08-18

from django.db import migrations, models


def seed_default_jenis_kompetensi(apps, schema_editor):
    JenisKompetensi = apps.get_model('idp', 'JenisKompetensi')
    defaults = [
        {'kode': 'TEKNIS', 'nama': 'Teknis', 'deskripsi': 'Kompetensi yang berkaitan dengan aspek teknis pelaksanaan tugas jabatan.'},
        {'kode': 'MANAJERIAL', 'nama': 'Manajerial', 'deskripsi': 'Kompetensi yang berkaitan dengan aspek manajerial pelaksanaan tugas jabatan.'},
        {'kode': 'SOSKUL', 'nama': 'Sosial Kultural', 'deskripsi': 'Kompetensi yang berkaitan dengan aspek sosial kultural pelaksanaan tugas jabatan.'},
    ]
    for item in defaults:
        JenisKompetensi.objects.get_or_create(
            nama=item['nama'],
            defaults=item
        )


def reverse_seed_default_jenis_kompetensi(apps, schema_editor):
    JenisKompetensi = apps.get_model('idp', 'JenisKompetensi')
    JenisKompetensi.objects.filter(
        nama__in=['Teknis', 'Manajerial', 'Sosial Kultural']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0004_remove_idpasn_jabatan_dasar_atau_alasan'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisKompetensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, default='', help_text='Kode singkat jenis kompetensi', max_length=20, verbose_name='Kode')),
                ('nama', models.CharField(help_text='Nama jenis kompetensi', max_length=150, verbose_name='Nama Jenis Kompetensi')),
                ('deskripsi', models.TextField(blank=True, default='', help_text='Deskripsi jenis kompetensi', verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tanggal Diupdate')),
            ],
            options={
                'verbose_name': 'Jenis Kompetensi',
                'verbose_name_plural': 'Jenis Kompetensi',
                'db_table': 'idp_jenis_kompetensi',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(
            seed_default_jenis_kompetensi,
            reverse_seed_default_jenis_kompetensi,
        ),
    ]
