# Generated by Django 4.2 on 2026-08-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0005_jeniskompetensi'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamaKompetensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, default='', help_text='Kode singkat nama kompetensi', max_length=20, verbose_name='Kode')),
                ('nama', models.CharField(help_text='Nama kompetensi', max_length=150, verbose_name='Nama Kompetensi')),
                ('deskripsi', models.TextField(blank=True, default='', help_text='Deskripsi nama kompetensi', verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tanggal Diupdate')),
                ('jenis_kompetensi', models.ForeignKey(help_text='Jenis kompetensi yang menaungi nama kompetensi ini', on_delete=django.db.models.deletion.CASCADE, related_name='nama_kompetensi', to='idp.jeniskompetensi', verbose_name='Jenis Kompetensi')),
            ],
            options={
                'verbose_name': 'Nama Kompetensi',
                'verbose_name_plural': 'Nama Kompetensi',
                'db_table': 'idp_nama_kompetensi',
                'ordering': ['jenis_kompetensi__id', 'id'],
            },
        ),
    ]