# Generated by Django 5.2.7 on 2026-08-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0006_namakompetensi'),
    ]

    operations = [
        migrations.AddField(
            model_name='namakompetensi',
            name='justifikasi_pengembangan',
            field=models.TextField(blank=True, default='', help_text='Alasan mengapa kompetensi ini penting untuk dikembangkan dan kaitannya dengan pekerjaan / kinerja', verbose_name='Justifikasi Pengembangan Kompetensi'),
        ),
        migrations.AddField(
            model_name='namakompetensi',
            name='prioritas_pengembangan',
            field=models.CharField(blank=True, choices=[('Sangat Tinggi', 'Sangat Tinggi'), ('Tinggi', 'Tinggi'), ('Sedang', 'Sedang'), ('Rendah', 'Rendah')], help_text='Tingkat prioritas pengembangan kompetensi ini', max_length=20, null=True, verbose_name='Prioritas Pengembangan'),
        ),
    ]
