# Generated by Django 5.2.7 on 2026-08-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0007_namakompetensi_prioritas_justifikasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrioritasPengembangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat_prioritas', models.CharField(choices=[('Sangat Tinggi', 'Sangat Tinggi'), ('Tinggi', 'Tinggi'), ('Sedang', 'Sedang'), ('Rendah', 'Rendah')], help_text='Tingkat prioritas pengembangan kompetensi ini', max_length=20, verbose_name='Tingkat Prioritas')),
                ('justifikasi_pengembangan', models.TextField(blank=True, default='', help_text='Alasan mengapa kompetensi ini penting untuk dikembangkan dan kaitannya dengan pekerjaan / kinerja', verbose_name='Justifikasi Pengembangan Kompetensi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tanggal Diupdate')),
            ],
            options={
                'verbose_name': 'Prioritas Pengembangan',
                'verbose_name_plural': 'Prioritas Pengembangan',
                'db_table': 'idp_prioritas_pengembangan',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='namakompetensi',
            name='justifikasi_pengembangan',
        ),
        migrations.RemoveField(
            model_name='namakompetensi',
            name='prioritas_pengembangan',
        ),
    ]
