# Generated by Django 5.2.7 on 2026-08-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0009_seed_prioritas_pengembangan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prioritaspengembangan',
            name='justifikasi_pengembangan',
        ),
        migrations.AlterField(
            model_name='prioritaspengembangan',
            name='tingkat_prioritas',
            field=models.CharField(help_text='Tingkat prioritas pengembangan kompetensi (bebas, contoh: Sangat Tinggi, Tinggi, Sedang, Rendah)', max_length=60, verbose_name='Tingkat Prioritas'),
        ),
    ]
