# Generated by Django 5.2.7 on 2026-08-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0015_metode_bentuk_pengembangan_revisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilarpengembangan',
            name='persentase',
            field=models.PositiveIntegerField(default=0, help_text='Porsi/bobot metode dalam pengembangan kompetensi (mis. 70, 20, 10)', verbose_name='Persentase (%)'),
        ),
    ]
