# Generated by Django 5.2.7 on 2026-08-20 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0016_alter_pilarpengembangan_persentase'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamaKegiatanProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Nama spesifik kegiatan atau program pengembangan kompetensi', max_length=250, verbose_name='Nama Kegiatan / Program')),
                ('deskripsi', models.TextField(blank=True, default='', help_text='Deskripsi kegiatan/program pengembangan kompetensi', verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tanggal Diupdate')),
                ('bentuk_pengembangan', models.ForeignKey(help_text='Bentuk pengembangan kompetensi yang menaungi kegiatan/program ini', on_delete=django.db.models.deletion.CASCADE, related_name='nama_kegiatan', to='idp.jeniskegiatanpengembangan', verbose_name='Bentuk Pengembangan Kompetensi')),
            ],
            options={
                'verbose_name': 'Nama Kegiatan / Program',
                'verbose_name_plural': 'Nama Kegiatan / Program',
                'db_table': 'idp_nama_kegiatan_program',
                'ordering': ['bentuk_pengembangan__id', 'id'],
            },
        ),
    ]
