# Generated by Django 5.2.7 on 2026-08-27 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0017_namakegiatanprogram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idpasn',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Waktu IDP diverifikasi', null=True, verbose_name='Waktu Verifikasi'),
        ),
        migrations.AddField(
            model_name='idpasn',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='User (atasan) yang melakukan verifikasi IDP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idp_verified', to=settings.AUTH_USER_MODEL, verbose_name='Diverifikasi Oleh'),
        ),
        migrations.AlterField(
            model_name='idpasn',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan'), ('verified', 'Diverifikasi'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='draft', help_text='Status IDP', max_length=20, verbose_name='Status'),
        ),
    ]
