# Generated by Django 5.2.7 on 2026-08-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0018_idpasn_verified_at_idpasn_verified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idpasn',
            name='alokasi_dukungan_program',
            field=models.TextField(blank=True, default='', help_text='Alokasi dukungan program untuk pengembangan kompetensi ini', verbose_name='Alokasi Dukungan Program'),
        ),
        migrations.AddField(
            model_name='idpasn',
            name='catatan_persetujuan',
            field=models.TextField(blank=True, default='', help_text='Catatan atau masukan dari kepala unit kerja terkait IDP ini', verbose_name='Catatan Persetujuan'),
        ),
    ]
