# Generated by Django 5.2.7 on 2026-08-27 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp', '0019_idpasn_alokasi_dukungan_program_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdpRevisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', help_text='Status sebelum perubahan', max_length=20, verbose_name='Status Awal')),
                ('to_status', models.CharField(blank=True, default='', help_text='Status setelah perubahan', max_length=20, verbose_name='Status Tujuan')),
                ('catatan', models.TextField(blank=True, default='', help_text='Catatan/alas an terkait transisi ini', verbose_name='Catatan')),
                ('alokasi_dukungan_program', models.TextField(blank=True, default='', help_text='Alokasi dukungan program (jika ada)', verbose_name='Alokasi Dukungan Program')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idp_revision_logs', to=settings.AUTH_USER_MODEL, verbose_name='Pelaku')),
                ('idp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat', to='idp.idpasn', verbose_name='IDP ASN')),
            ],
            options={
                'verbose_name': 'Riwayat Revisi IDP',
                'verbose_name_plural': 'Riwayat Revisi IDP',
                'db_table': 'idp_revision_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
