"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add apps directory to Python path
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,0.0.0.0,192.1.6.21').split(',')

# CSRF Trusted Origins (for frontend requests)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://192.1.6.21:3000',
    'http://192.1.6.6:3000',
    'http://192.168.1.12:3000',
    'http://192.1.6.43:3000',
    'http://103.143.152.139:3000',
]

# Trust proxy headers for correct host/port detection
USE_X_FORWARDED_HOST = config('USE_X_FORWARDED_HOST', default=True, cast=bool)
USE_X_FORWARDED_PORT = config('USE_X_FORWARDED_PORT', default=True, cast=bool)


# App branding (used by core.context_processors.app_branding)
APP_NAME = config('APP_NAME', default='asncorpu-backend')
APP_LONG_NAME = config('APP_LONG_NAME', default='ASN Corpu Backend System')
APP_INSTANSI = config('APP_INSTANSI', default='ASN Corpu Organization')
APP_DESCRIPTION = config('APP_DESCRIPTION', default='Backend system for ASN Corpu platform')

# Internal key prefix (cache/redis)
APP_KEY_PREFIX = config('APP_KEY_PREFIX', default='asncorpu-backend')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',  # JWT Authentication
    'corsheaders',
    'django_extensions',
    'django_filters',
    'django_tables2',  # DataTable functionality with Tailwind
    # 'django_plotly_dash.apps.DjangoPlotlyDashConfig',  # Removed - not used
    
    # Local apps
    'core',  # Core models (API logging, etc)
    'apps.accounts',  # Custom User Model - MUST be before other apps that use User
    'apps.dashboard',
    'apps.manajemen',  # Centralized Permission Management (renamed from permissions)
    'apps.knowledge',  # Knowledge Base (KMS) - Articles, Categories, Tags
    'apps.integrations',  # Password Sync Pipeline - Compatible with ESIMPEG
    'apps.hcdp',  # HCDP (Human Capital Development Program)
    'apps.profile',  # Profile Instansi
    'apps.learning',  # Learning Management System (LMS)
    'apps.news',  # News/Berita
    'apps.hero',  # Hero Images for Landing Page
]

# Custom User Model - match Laravel users table structure
AUTH_USER_MODEL = 'accounts.User'

# Authentication Backends - Support login dengan Username/Email/NIP + ESIMPEG Fallback
AUTHENTICATION_BACKENDS = [
    'apps.accounts.backends.FlexibleAuthBackend',  # Custom: username/email/NIP + ESIMPEG fallback
    'django.contrib.auth.backends.ModelBackend',   # Fallback: standard Django auth
]

# ESIMPEG Integration Settings
ESIMPEG_FALLBACK_ENABLED = config('ESIMPEG_FALLBACK_ENABLED', default=True, cast=bool)
ESIMPEG_API_URL = config('ESIMPEG_API_URL', default='http://localhost:8005')
ESIMPEG_API_TIMEOUT = config('ESIMPEG_API_TIMEOUT', default=10, cast=int)

# Password Hashers - Universal format (Argon2 recommended by OWASP)
# Priority order: Django akan menggunakan hasher pertama untuk NEW passwords
# Hasher lainnya digunakan untuk VERIFY existing passwords
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',       # ⭐ NEW PASSWORDS (most secure, OWASP recommended)
    'django.contrib.auth.hashers.BCryptPasswordHasher',       # Standard bcrypt (universal, cross-platform)
    'apps.accounts.hashers.LaravelBcryptPasswordHasher',      # Laravel $2y$ compatibility (for old passwords)
    'apps.accounts.hashers.LaravelCompatibleBcryptHasher',    # Bcrypt fallback
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher', # Django bcrypt with SHA256
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',       # Django default
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',   # Legacy
]

# Authentication URLs
LOGIN_URL = '/'  # Landing page adalah halaman login
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = 'http://localhost:3000/'  # Redirect ke Next.js landing page setelah logout (via Nginx)

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS - Must be at the top
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.csrf_exempt.CSRFExemptMiddleware',  # CSRF exempt for API endpoints
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.SessionInactivityMiddleware',  # From middleware.py - Auto-logout on inactivity
    # 'core.middleware.ForceChangePasswordMiddleware',  # DISABLED - Force change default password
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.manajemen.middleware.AdminAccessMiddleware',  # Restrict /admin/ to superusers only
    'core.middleware.api_logging.APILoggingMiddleware',  # Hybrid API logging (file + database)
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'apps' / 'manajemen' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.app_branding',  # Auto-inject app_name, app_long_name, app_instansi
                'apps.manajemen.context_processors.sidebar_menu',  # Dynamic sidebar from DB menus
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

ASGI_APPLICATION = 'core.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Use MySQL if available, fall back to SQLite
if config('DB_HOST', default=None):
    DATABASES = {
        'default': {
            'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
            'NAME': config('DB_NAME', default='asncorpu_backend_db'),
            'USER': config('DB_USER', default='asncorpu_user'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='asncorpu-backend-postgres'),
            'PORT': config('DB_PORT', default=5432, cast=int),
            'OPTIONS': {
                'connect_timeout': 10,
            } if config('DB_ENGINE', default='django.db.backends.postgresql') == 'django.db.backends.postgresql' else {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        },
        # Laravel Database Connection (For API Documentation)
        # Uses separate connection to read from existing Laravel database
        'laravel': {
            'ENGINE': config('LARAVEL_DB_ENGINE', default=config('DB_ENGINE', default='django.db.backends.mysql')),
            'NAME': config('LARAVEL_DB_NAME', default='asncorpu_laravel_db'),
            'USER': config('LARAVEL_DB_USER', default=config('DB_USER', default='root')),
            'PASSWORD': config('LARAVEL_DB_PASSWORD', default=config('DB_PASSWORD')),
            'HOST': config('LARAVEL_DB_HOST', default=config('DB_HOST', default='mysql-main')),
            'PORT': config('LARAVEL_DB_PORT', default=config('DB_PORT', default=3306), cast=int),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        },
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'id'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Whitenoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redis Configuration
REDIS_HOST = config('REDIS_HOST', default='redis-main')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)
REDIS_PASSWORD = config('REDIS_PASSWORD', default='')
REDIS_DB = config('REDIS_DB', default=3, cast=int)

# Cache Configuration (Redis - FAST!)
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'PASSWORD': REDIS_PASSWORD,
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True
            }
        },
        'KEY_PREFIX': APP_KEY_PREFIX,
        'TIMEOUT': 300,  # 5 minutes default cache timeout
    }
}

# Session Configuration (Redis - SUPER FAST!)
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'  # Use Redis for sessions
SESSION_CACHE_ALIAS = 'default'  # Use default cache (Redis)
SESSION_COOKIE_AGE = 1800  # 30 minutes (default session age)
SESSION_SAVE_EVERY_REQUEST = True  # Update session on every request (track activity)
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SECURE = False  # Set True in production (HTTPS only)

# Custom: Inactivity timeout (in seconds)
SESSION_INACTIVITY_TIMEOUT = 1800  # 30 minutes of inactivity = auto logout

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT Authentication
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.PerPagePagination',
    'PAGE_SIZE': 25,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
}

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Nginx reverse proxy (main access point)
    "http://127.0.0.1:3000",
    "http://localhost:8007",
    "http://127.0.0.1:8007",
    "http://192.1.6.16:3000", # External access via Nginx
    "http://192.1.6.21:3000", # Laptop access
    "http://192.1.6.6:3000",  # Server ethernet
    "http://192.168.1.12:3000", # Server wifi
    "http://192.1.6.43:3000", # IP lain di network
    "http://103.143.152.139:3000", # Public VPS IP
]

# Additional CORS settings for API access
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CORS Methods
CORS_ALLOWED_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# CORS Preflight
CORS_PREFLIGHT_MAX_AGE = 86400

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'api_access': {
            'format': '%(message)s',  # Just the message (already JSON formatted)
        },
    },
    'handlers': {
        'file': {
            'level': config('LOG_LEVEL', default='INFO'),
            'class': 'logging.FileHandler',
            'filename': config('LOG_FILE', default=BASE_DIR / 'logs' / 'django.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'api_access_file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'api_access.log',
            'when': 'midnight',  # Rotate daily at midnight
            'interval': 1,
            'backupCount': 365,  # Keep 1 year (365 days) of logs
            'formatter': 'api_access',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'api_access': {
            'handlers': ['api_access_file'],
            'level': 'INFO',
            'propagate': False,  # Don't propagate to root logger
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# File Upload and Request Body Settings
# Increased limits for handling large data (e.g., 9000+ records from API)
FILE_UPLOAD_MAX_MEMORY_SIZE = config('MAX_UPLOAD_SIZE', default=134217728, cast=int)  # 128MB (was 10MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = config('DJANGO_MAX_REQUEST_SIZE', default=134217728, cast=int)  # 128MB for request body
DATA_UPLOAD_MAX_NUMBER_FIELDS = 20000  # Increased from default 1000 (for large forms/JSON with many fields)

# Security Settings (for production)
if not DEBUG:
    # Force HTTPS redirect (can be disabled via env for testing)
    # Use os.environ directly for reliable boolean parsing
    _ssl_redirect = os.environ.get('SECURE_SSL_REDIRECT', 'True').lower() in ('true', '1', 'yes')
    SECURE_SSL_REDIRECT = _ssl_redirect
    
    # HSTS (HTTP Strict Transport Security) - only if SSL redirect is enabled
    if SECURE_SSL_REDIRECT:
        SECURE_HSTS_SECONDS = 31536000  # 1 year
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True
    
    # Detect HTTPS behind proxy/load balancer
    # CRITICAL: For proper protocol detection (http vs https)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Secure cookies (only if using HTTPS)
    SESSION_COOKIE_SECURE = _ssl_redirect
    CSRF_COOKIE_SECURE = _ssl_redirect
    
    # Prevent browsers from guessing content type
    SECURE_CONTENT_TYPE_NOSNIFF = True
    
    # Enable XSS filter in browser
    SECURE_BROWSER_XSS_FILTER = True
    
    # Prevent clickjacking
    X_FRAME_OPTIONS = 'DENY'
else:
    # Development settings - Allow HTTP
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# JWT Settings (djangorestframework-simplejwt)
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),  # Token valid 24 jam
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),   # Refresh token valid 7 hari
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': config('JWT_ISSUER', default='asncorpu-backend'),
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Feature Flags
# Toggle single-device enforcement for NIP/NIK users across web & API
SINGLE_SESSION_ENFORCE_NIP_NIK = config('SINGLE_SESSION_ENFORCE_NIP_NIK', default=False, cast=bool)
SINGLE_SESSION_ENFORCE_WEB_NIP_NIK = config('SINGLE_SESSION_ENFORCE_WEB_NIP_NIK', default=True, cast=bool)
SINGLE_SESSION_ENFORCE_API_NIP_NIK = config('SINGLE_SESSION_ENFORCE_API_NIP_NIK', default=False, cast=bool)

# Permission system override flag (disable superadmin/staff bypass when False)
PERMISSIONS_SUPERADMIN_OVERRIDE = config('PERMISSIONS_SUPERADMIN_OVERRIDE', default=True, cast=bool)

# Admin access via permission keys (used by AdminAccessMiddleware)
ADMIN_ACCESS_PERMISSION_KEYS = [
    'pengaturan.manajemen_user.view',
    'pengaturan.manajemen_permission.view',
]
