# Generated by Django 5.2.7 on 2026-06-30 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MsPerguruanTinggi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_pddikti', models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='ID PDDIKTI')),
                ('kode_pt', models.CharField(max_length=10, unique=True, verbose_name='Kode PT')),
                ('nama_pt', models.CharField(max_length=255, verbose_name='Nama Perguruan Tinggi')),
                ('bentuk_pt', models.CharField(blank=True, help_text='Universitas, Institut, Politeknik, Sekolah Tinggi, Akademi', max_length=50, null=True, verbose_name='Bentuk PT')),
                ('status_pt', models.CharField(blank=True, help_text='Negeri / Swasta', max_length=10, null=True, verbose_name='Status')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('kota', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kota')),
                ('provinsi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provinsi')),
                ('telepon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telepon')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('akreditasi', models.CharField(blank=True, max_length=20, null=True, verbose_name='Akreditasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Perguruan Tinggi',
                'verbose_name_plural': 'Perguruan Tinggi',
                'db_table': 'Ms_perguruan_tinggi',
                'ordering': ['nama_pt'],
            },
        ),
        migrations.CreateModel(
            name='MsProgramStudi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_pddikti', models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='ID PDDIKTI')),
                ('kode_prodi', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kode Prodi')),
                ('nama_prodi', models.CharField(max_length=255, verbose_name='Nama Program Studi')),
                ('jenjang', models.CharField(blank=True, help_text='S1, S2, S3, D3, D4, Profesi, Spesialis', max_length=10, null=True, verbose_name='Jenjang')),
                ('akreditasi', models.CharField(blank=True, max_length=20, null=True, verbose_name='Akreditasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('perguruan_tinggi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_studi_set', to='referensi.msperguruantinggi', verbose_name='Perguruan Tinggi')),
            ],
            options={
                'verbose_name': 'Program Studi',
                'verbose_name_plural': 'Program Studi',
                'db_table': 'Ms_program_studi',
                'ordering': ['perguruan_tinggi__nama_pt', 'jenjang', 'nama_prodi'],
            },
        ),
    ]
