# Generated by Django 5.2.7 on 2026-07-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsInstansi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode_instansi', models.CharField(max_length=20, unique=True, verbose_name='Kode Instansi')),
                ('nama_instansi', models.CharField(max_length=255, verbose_name='Nama Instansi')),
                ('jenis_instansi', models.CharField(blank=True, help_text='Kementerian, Lembaga, Pemerintah Daerah, BUMN/BUMD, Lainnya', max_length=50, null=True, verbose_name='Jenis Instansi')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('telepon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telepon')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Instansi',
                'verbose_name_plural': 'Instansi',
                'db_table': 'Ms_instansi',
                'ordering': ['nama_instansi'],
            },
        ),
    ]
