# Generated by Django 5.2.7 on 2026-07-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0002_msinstansi'),
    ]

    operations = [
        migrations.AddField(
            model_name='msinstansi',
            name='id_bkn',
            field=models.CharField(blank=True, help_text='UUID dari referensi BKN', max_length=36, null=True, verbose_name='ID BKN'),
        ),
        migrations.AddField(
            model_name='msinstansi',
            name='tingkat_instansi',
            field=models.CharField(blank=True, help_text='Pusat / Daerah', max_length=10, null=True, verbose_name='Tingkat Instansi'),
        ),
        migrations.AlterField(
            model_name='msinstansi',
            name='jenis_instansi',
            field=models.CharField(blank=True, help_text='Kementerian Koordinator, Kementerian, LPNK, LNS, Provinsi, Kabupaten, Kota', max_length=50, null=True, verbose_name='Jenis Instansi'),
        ),
    ]
