# Generated by Django 5.2.7 on 2026-07-02 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0003_msinstansi_id_bkn_msinstansi_tingkat_instansi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsKabupaten',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=10, unique=True, verbose_name='Kode Kabupaten/Kota')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Kabupaten/Kota')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kabupaten/Kota',
                'verbose_name_plural': 'Kabupaten/Kota',
                'db_table': 'Ms_kabupaten',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='MsProvinsi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=10, unique=True, verbose_name='Kode Provinsi')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Provinsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Provinsi',
                'verbose_name_plural': 'Provinsi',
                'db_table': 'Ms_provinsi',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='MsKecamatan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=10, unique=True, verbose_name='Kode Kecamatan')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Kecamatan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kabupaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kecamatan_set', to='referensi.mskabupaten', verbose_name='Kabupaten/Kota')),
            ],
            options={
                'verbose_name': 'Kecamatan',
                'verbose_name_plural': 'Kecamatan',
                'db_table': 'Ms_kecamatan',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='MsKelurahan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=15, unique=True, verbose_name='Kode Kelurahan/Desa')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama Kelurahan/Desa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelurahan_set', to='referensi.mskecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name': 'Kelurahan/Desa',
                'verbose_name_plural': 'Kelurahan/Desa',
                'db_table': 'Ms_kelurahan',
                'ordering': ['kode'],
            },
        ),
        migrations.AddField(
            model_name='mskabupaten',
            name='provinsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kabupaten_set', to='referensi.msprovinsi', verbose_name='Provinsi'),
        ),
    ]
