# Generated by Django 5.2.7 on 2026-07-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0004_mskabupaten_msprovinsi_mskecamatan_mskelurahan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsKategoriUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kategori User',
                'verbose_name_plural': 'Kategori User',
                'db_table': 'Ms_kategori_user',
                'ordering': ['kode'],
            },
        ),
    ]
