# Generated by Django 5.2.7 on 2026-05-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama')),
                ('nip', models.CharField(blank=True, max_length=30, null=True, verbose_name='NIP')),
                ('position', models.CharField(max_length=255, verbose_name='Jabatan')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/personalia/%Y/%m/', verbose_name='Foto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telepon')),
                ('unit_kerja', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit Kerja / Bidang')),
                ('order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personalia',
                'verbose_name_plural': 'Personalia',
                'db_table': 'profile_personalia',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProfileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('sambutan', 'Sambutan'), ('visi_misi', 'Visi & Misi'), ('sejarah', 'Sejarah Corpu'), ('struktur_organisasi', 'Struktur Organisasi')], max_length=50, unique=True, verbose_name='Kunci')),
                ('title', models.CharField(max_length=255, verbose_name='Judul')),
                ('content', models.TextField(verbose_name='Konten')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/sections/%Y/%m/', verbose_name='Gambar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section Profile',
                'verbose_name_plural': 'Section Profile',
                'db_table': 'profile_sections',
                'ordering': ['order', 'key'],
            },
        ),
    ]
