# Generated by Django 5.2.7 on 2026-05-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama brand atau deskripsi logo', max_length=255, verbose_name='Nama Brand')),
                ('image', models.ImageField(help_text='Upload gambar brand/logo (PNG, JPG, SVG)', upload_to='profile/brands/%Y/%m/', verbose_name='Gambar Brand')),
                ('description', models.TextField(blank=True, help_text='Deskripsi atau keterangan brand', null=True, verbose_name='Deskripsi')),
                ('is_primary', models.BooleanField(default=False, help_text='Tandai sebagai brand utama institusi', verbose_name='Brand Utama')),
                ('is_active', models.BooleanField(default=True, help_text='Status aktif brand', verbose_name='Aktif')),
                ('order', models.IntegerField(default=0, help_text='Urutan tampilan brand', verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'profile_brands',
                'ordering': ['order', '-is_primary', 'name'],
            },
        ),
    ]
