# Generated by Django 5.2.7 on 2026-05-25 09:42

import apps.profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(help_text='Upload gambar brand/logo (PNG, JPG, SVG)', upload_to=apps.profile.models.brand_upload_to, verbose_name='Gambar Brand'),
        ),
        migrations.AlterField(
            model_name='personalia',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.profile.models.personalia_upload_to, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='profilesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.profile.models.section_upload_to, verbose_name='Gambar'),
        ),
    ]
