# Generated by Django 5.2.7 on 2026-06-25 18:44

import apps.hero.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('image', models.ImageField(help_text='Rekomendasi: ukuran 400x400 px (1:1 square)', upload_to=apps.hero.models.hero_image_upload_to, verbose_name='Gambar')),
                ('order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Images',
                'db_table': 'hero_images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
