# Generated by Django 5.2.7 on 2026-06-25 18:59

import apps.hero.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Rekomendasi: ukuran 400x400 px (1:1 square)', null=True, upload_to=apps.hero.models.hero_image_upload_to, verbose_name='Gambar'),
        ),
    ]
