# Generated by Django 5.2.7 on 2026-05-19 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HcdpProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(help_text='Judul program HCDP', max_length=255, verbose_name='Judul Program')),
                ('deskripsi', models.TextField(help_text='Deskripsi lengkap program HCDP', verbose_name='Deskripsi')),
                ('gambar', models.ImageField(blank=True, help_text='Gambar ilustrasi program (optional)', null=True, upload_to='hcdp/%Y/%m/', verbose_name='Gambar')),
                ('is_active', models.BooleanField(default=True, help_text='Status aktif program', verbose_name='Aktif')),
                ('is_published', models.BooleanField(default=False, help_text='Apakah program ditampilkan di halaman public', verbose_name='Dipublikasikan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tanggal Diupdate')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hcdp_programs_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Program HCDP',
                'verbose_name_plural': 'Program HCDP',
                'db_table': 'hcdp_programs',
                'ordering': ['-created_at'],
            },
        ),
    ]
