# Generated by Django 5.2.7 on 2026-05-25 09:44

import apps.hcdp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcdp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hcdpprogram',
            name='gambar',
            field=models.ImageField(blank=True, help_text='Gambar ilustrasi program (optional)', null=True, upload_to=apps.hcdp.models.hcdp_upload_to, verbose_name='Gambar'),
        ),
    ]
