# Generated by Django 5.2.7 on 2026-06-02 16:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Judul Pelajaran')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Konten')),
                ('content_type', models.CharField(choices=[('article', 'Artikel'), ('video', 'Video'), ('document', 'Dokumen'), ('link', 'Link Eksternal'), ('quiz', 'Kuis')], default='article', max_length=20, verbose_name='Tipe Konten')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL Video')),
                ('video_embed_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Video Embed ID')),
                ('file_url', models.FileField(blank=True, null=True, upload_to='lessons/', verbose_name='File')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='URL Eksternal')),
                ('duration_minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Durasi (Menit)')),
                ('order_index', models.IntegerField(default=0, verbose_name='Urutan')),
                ('is_free', models.BooleanField(default=True, verbose_name='Gratis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
            ],
            options={
                'verbose_name': 'Pelajaran',
                'verbose_name_plural': 'Pelajaran',
                'db_table': 'learning_lessons',
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Judul Kursus')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('short_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Deskripsi Singkat')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Thumbnail')),
                ('level', models.CharField(choices=[('beginner', 'Pemula'), ('intermediate', 'Menengah'), ('advanced', 'Lanjutan')], default='beginner', max_length=20, verbose_name='Level')),
                ('duration_hours', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Durasi (Jam)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Dipublikasikan'), ('archived', 'Diarsipkan')], default='draft', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Dipublikasi Pada')),
                ('enrolled_count', models.IntegerField(default=0, verbose_name='Jumlah Pendaftar')),
                ('lesson_count', models.IntegerField(default=0, verbose_name='Jumlah Pelajaran')),
                ('rating_avg', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating Rata-rata')),
                ('rating_count', models.IntegerField(default=0, verbose_name='Jumlah Rating')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name='Instruktur')),
            ],
            options={
                'verbose_name': 'Kursus',
                'verbose_name_plural': 'Kursus',
                'db_table': 'learning_courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(verbose_name='Komentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='learning.course', verbose_name='Kursus')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='learning.coursecomment', verbose_name='Komentar Induk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_comments', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Komentar Kursus',
                'verbose_name_plural': 'Komentar Kursus',
                'db_table': 'learning_course_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseCommentLike',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='learning.coursecomment', verbose_name='Komentar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Suka Komentar',
                'verbose_name_plural': 'Suka Komentar',
                'db_table': 'learning_comment_likes',
            },
        ),
        migrations.CreateModel(
            name='CourseLike',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='learning.course', verbose_name='Kursus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_courses', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Suka Kursus',
                'verbose_name_plural': 'Suka Kursus',
                'db_table': 'learning_course_likes',
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Komentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='learning.course', verbose_name='Kursus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Rating Kursus',
                'verbose_name_plural': 'Rating Kursus',
                'db_table': 'learning_course_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('completed', 'Selesai'), ('dropped', 'Berhenti')], default='active', max_length=20, verbose_name='Status')),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progres (%)')),
                ('has_certificate', models.BooleanField(default=False, verbose_name='Memiliki Sertifikat')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Mendaftar Pada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Selesai Pada')),
                ('last_accessed_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Diakses')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.course', verbose_name='Kursus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Pendaftaran',
                'verbose_name_plural': 'Pendaftaran',
                'db_table': 'learning_enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=100, unique=True, verbose_name='Nomor Sertifikat')),
                ('user_name', models.CharField(max_length=255, verbose_name='Nama Pengguna')),
                ('course_title', models.CharField(max_length=255, verbose_name='Judul Kursus')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Diterbitkan Pada')),
                ('pdf_url', models.URLField(blank=True, null=True, verbose_name='URL PDF')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='learning.enrollment', verbose_name='Pendaftaran')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikat',
                'db_table': 'learning_certificates',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False, verbose_name='Selesai')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Selesai Pada')),
                ('time_spent_minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Waktu (Menit)')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='learning.enrollment', verbose_name='Pendaftaran')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.lesson', verbose_name='Pelajaran')),
            ],
            options={
                'verbose_name': 'Progres Pelajaran',
                'verbose_name_plural': 'Progres Pelajaran',
                'db_table': 'learning_lesson_progress',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Judul Modul')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('order_index', models.IntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.course', verbose_name='Kursus')),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modul',
                'db_table': 'learning_modules',
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.module', verbose_name='Modul'),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Judul Kuis')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('passing_score_percentage', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nilai Lulus (%)')),
                ('max_attempts', models.IntegerField(default=1, help_text='-1 untuk tidak terbatas', verbose_name='Maksimal Percobaan')),
                ('is_randomized', models.BooleanField(default=False, verbose_name='Acak Pertanyaan')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Jumlah Pertanyaan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='learning.lesson', verbose_name='Pelajaran')),
            ],
            options={
                'verbose_name': 'Kuis',
                'verbose_name_plural': 'Kuis',
                'db_table': 'learning_quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0, verbose_name='Skor')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Jumlah Pertanyaan')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Jawaban Benar')),
                ('passed', models.BooleanField(default=False, verbose_name='Lulus')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Mulai Pada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Selesai Pada')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.enrollment', verbose_name='Pendaftaran')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.quiz', verbose_name='Kuis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Percobaan Kuis',
                'verbose_name_plural': 'Percobaan Kuis',
                'db_table': 'learning_quiz_attempts',
                'ordering': ['-completed_at', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField(verbose_name='Teks Pertanyaan')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Pilihan Ganda'), ('true_false', 'Benar/Salah'), ('essay', 'Esai')], default='multiple_choice', max_length=20, verbose_name='Tipe Pertanyaan')),
                ('order_index', models.IntegerField(default=0, verbose_name='Urutan')),
                ('points', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Poin')),
                ('essay_word_limit', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Batas Kata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.quiz', verbose_name='Kuis')),
            ],
            options={
                'verbose_name': 'Pertanyaan Kuis',
                'verbose_name_plural': 'Pertanyaan Kuis',
                'db_table': 'learning_quiz_questions',
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('choice_text', models.TextField(verbose_name='Teks Pilihan')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Benar')),
                ('order_index', models.IntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learning.quizquestion', verbose_name='Pertanyaan')),
            ],
            options={
                'verbose_name': 'Pilihan Jawaban',
                'verbose_name_plural': 'Pilihan Jawaban',
                'db_table': 'learning_quiz_choices',
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_correct_bool', models.BooleanField(blank=True, null=True, verbose_name='Benar/Salah')),
                ('essay_answer', models.TextField(blank=True, null=True, verbose_name='Jawaban Esai')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Benar')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Poin Diperoleh')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.quizattempt', verbose_name='Percobaan')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.quizchoice', verbose_name='Pilihan Dipilih')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.quizquestion', verbose_name='Pertanyaan')),
            ],
            options={
                'verbose_name': 'Jawaban Kuis',
                'verbose_name_plural': 'Jawaban Kuis',
                'db_table': 'learning_quiz_answers',
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='learning_co_slug_873315_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='learning_co_status_9de4ce_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor'], name='learning_co_instruc_9edb41_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_featured'], name='learning_co_is_feat_decfa3_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecomment',
            index=models.Index(fields=['course'], name='learning_co_course__92bae9_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecomment',
            index=models.Index(fields=['user'], name='learning_co_user_id_f9105a_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecommentlike',
            index=models.Index(fields=['comment'], name='learning_co_comment_f1484e_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecommentlike',
            index=models.Index(fields=['user'], name='learning_co_user_id_4fbe5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursecommentlike',
            unique_together={('comment', 'user')},
        ),
        migrations.AddIndex(
            model_name='courselike',
            index=models.Index(fields=['course'], name='learning_co_course__eff53f_idx'),
        ),
        migrations.AddIndex(
            model_name='courselike',
            index=models.Index(fields=['user'], name='learning_co_user_id_7d4af2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courselike',
            unique_together={('course', 'user')},
        ),
        migrations.AddIndex(
            model_name='courserating',
            index=models.Index(fields=['course'], name='learning_co_course__57e870_idx'),
        ),
        migrations.AddIndex(
            model_name='courserating',
            index=models.Index(fields=['user'], name='learning_co_user_id_51692b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courserating',
            unique_together={('course', 'user')},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course'], name='learning_en_course__69e6f4_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user'], name='learning_en_user_id_f49550_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status'], name='learning_en_status_41b066_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('course', 'user')},
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['enrollment'], name='learning_ce_enrollm_a8595d_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_number'], name='learning_ce_certifi_bbcba3_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['enrollment'], name='learning_le_enrollm_fb3bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['is_completed'], name='learning_le_is_comp_57ac54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('enrollment', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course'], name='learning_mo_course__407377_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'order_index')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module'], name='learning_le_module__f18a50_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['content_type'], name='learning_le_content_83d8aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'slug')},
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['lesson'], name='learning_qu_lesson__7ed7ee_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz'], name='learning_qu_quiz_id_76cbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user'], name='learning_qu_user_id_fb08d6_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['passed'], name='learning_qu_passed_312829_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz'], name='learning_qu_quiz_id_996161_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['question_type'], name='learning_qu_questio_979c75_idx'),
        ),
        migrations.AddIndex(
            model_name='quizchoice',
            index=models.Index(fields=['question'], name='learning_qu_questio_9ddf30_idx'),
        ),
        migrations.AddIndex(
            model_name='quizchoice',
            index=models.Index(fields=['is_correct'], name='learning_qu_is_corr_d4dbd2_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['attempt'], name='learning_qu_attempt_0efb09_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['is_correct'], name='learning_qu_is_corr_8cf2a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
