# Generated by Django 5.2.7 on 2026-06-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Thumbnail'),
        ),
    ]
