# Generated by Django 5.2.7 on 2026-06-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dinilai Pada'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='grader_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan Penilai'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='is_graded',
            field=models.BooleanField(default=False, verbose_name='Dinilai'),
        ),
    ]
