# Generated by Django 5.2.7 on 2026-06-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_add_essay_grading_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSetting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(default='ASN CorpU', max_length=255, verbose_name='Nama Institusi')),
                ('signature_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nama Penandatangan')),
                ('signature_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Jabatan Penandatangan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Logo')),
                ('background', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Background')),
                ('show_course_hours', models.BooleanField(default=True, verbose_name='Tampilkan Durasi Kursus')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Pengaturan Sertifikat',
                'verbose_name_plural': 'Pengaturan Sertifikat',
                'db_table': 'learning_certificate_settings',
            },
        ),
    ]
