# Generated by Django 5.2.7 on 2026-06-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_certificatesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatesetting',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Gambar Tanda Tangan'),
        ),
    ]
