# Generated by Django 5.2.7 on 2026-06-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_certificatesetting_signature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatesetting',
            name='tte_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/tte/', verbose_name='Sertifikat TTE'),
        ),
        migrations.AddField(
            model_name='certificatesetting',
            name='tte_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='TTE Dibuat Pada'),
        ),
        migrations.AddField(
            model_name='certificatesetting',
            name='tte_enabled',
            field=models.BooleanField(default=False, verbose_name='Aktifkan TTE'),
        ),
        migrations.AddField(
            model_name='certificatesetting',
            name='tte_passphrase',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Passphrase TTE'),
        ),
        migrations.AddField(
            model_name='certificatesetting',
            name='tte_private_key',
            field=models.FileField(blank=True, null=True, upload_to='certificates/tte/', verbose_name='Private Key TTE'),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_background',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Background Sertifikat'),
        ),
    ]
