# Generated by Django 5.2.7 on 2026-06-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_certificatesetting_tte_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.FileField(blank=True, null=True, upload_to='certificates/templates/', verbose_name='Template Sertifikat (HTML)'),
        ),
    ]
