# Generated by Django 5.2.7 on 2026-06-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_course_certificate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
    ]
