# Generated by Django 5.2.7 on 2026-06-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_certificate_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cert_institution_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nama Institusi (Override)'),
        ),
        migrations.AddField(
            model_name='course',
            name='cert_logo',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Logo (Override)'),
        ),
        migrations.AddField(
            model_name='course',
            name='cert_show_course_hours',
            field=models.BooleanField(blank=True, null=True, verbose_name='Tampilkan Durasi (Override)'),
        ),
        migrations.AddField(
            model_name='course',
            name='cert_signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Tanda Tangan (Override)'),
        ),
        migrations.AddField(
            model_name='course',
            name='cert_signature_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nama Penandatangan (Override)'),
        ),
        migrations.AddField(
            model_name='course',
            name='cert_signature_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Jabatan Penandatangan (Override)'),
        ),
    ]
