# Generated by Django 5.2.7 on 2026-06-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_course_cert_institution_name_course_cert_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatesetting',
            name='cert_number_format',
            field=models.CharField(blank=True, default='{PREFIX}-{DATE}-{RANDOM}', help_text='Variable: {PREFIX}, {DATE}, {RANDOM}, {YEAR}, {MONTH}, {DAY}, {COURSE_ID}, {USER_ID}', max_length=50, verbose_name='Format Nomor Sertifikat'),
        ),
        migrations.AddField(
            model_name='certificatesetting',
            name='cert_number_prefix',
            field=models.CharField(blank=True, default='CERT', max_length=50, verbose_name='Prefix Nomor Sertifikat'),
        ),
        migrations.AddField(
            model_name='course',
            name='cert_tte_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/tte/', verbose_name='Sertifikat TTE (Khusus)'),
        ),
        migrations.AddField(
            model_name='course',
            name='cert_tte_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='TTE Dibuat (Khusus)'),
        ),
        migrations.AddField(
            model_name='course',
            name='cert_tte_enabled',
            field=models.BooleanField(default=False, verbose_name='TTE Khusus'),
        ),
        migrations.AddField(
            model_name='course',
            name='cert_tte_passphrase',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Passphrase TTE (Khusus)'),
        ),
        migrations.AddField(
            model_name='course',
            name='cert_tte_private_key',
            field=models.FileField(blank=True, null=True, upload_to='certificates/tte/', verbose_name='Private Key TTE (Khusus)'),
        ),
    ]
