# Generated by Django 5.2.7 on 2026-06-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_certificatesetting_cert_number_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cert_number_format',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Format Nomor (Override)'),
        ),
        migrations.AddField(
            model_name='course',
            name='cert_number_prefix',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Prefix Nomor (Override)'),
        ),
    ]
