# Generated by Django 5.2.7 on 2026-06-03 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_course_cert_number_format_course_cert_number_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.IntegerField(default=0, help_text='0 = tanpa batas waktu', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Batas Waktu (Menit)'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_spent',
            field=models.IntegerField(default=0, verbose_name='Waktu (detik)'),
        ),
    ]
