# Generated by Django 5.2.7 on 2026-06-12 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_add_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration_hours',
        ),
        migrations.AddField(
            model_name='course',
            name='duration_minutes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Durasi (Menit)'),
        ),
    ]
