# Generated by Django 5.2.7 on 2026-06-12 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_remove_course_duration_hours_course_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='retry_cooldown_minutes',
            field=models.IntegerField(default=0, help_text='0 = tidak ada cooldown. 1440 = 24 jam (jam yang sama besok)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cooldown sebelum retry (menit)'),
        ),
    ]
