# Generated by Django 5.2.7 on 2026-06-23 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_quiz_retry_cooldown_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='time_spent_minutes',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Waktu (Menit)'),
        ),
    ]
