# Generated by Django 5.2.7 on 2026-06-29 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Sync')),
                ('total_records', models.IntegerField(default=0, verbose_name='Total Records')),
                ('new_records', models.IntegerField(default=0, verbose_name='Records Baru')),
                ('updated_records', models.IntegerField(default=0, verbose_name='Records Diupdate')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='success', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Durasi (detik)')),
                ('synced_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Di-sync oleh')),
            ],
            options={
                'verbose_name': 'Log Sinkronisasi',
                'verbose_name_plural': 'Log Sinkronisasi',
                'db_table': 'api_simpeg_sync_log',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.CharField(max_length=50, unique=True, verbose_name='Sync ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20, verbose_name='Status')),
                ('current_page', models.IntegerField(default=0, verbose_name='Current Page')),
                ('total_pages', models.IntegerField(default=0, verbose_name='Total Pages')),
                ('processed_records', models.IntegerField(default=0, verbose_name='Processed Records')),
                ('total_records', models.IntegerField(default=0, verbose_name='Total Records')),
                ('new_records', models.IntegerField(default=0, verbose_name='New Records')),
                ('updated_records', models.IntegerField(default=0, verbose_name='Updated Records')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Sync Progress',
                'verbose_name_plural': 'Sync Progress',
                'db_table': 'api_simpeg_sync_progress',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pegawai', models.BigIntegerField(db_index=True, unique=True, verbose_name='ID Pegawai')),
                ('nip_baru', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='NIP Baru')),
                ('nip_lama', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIP Lama')),
                ('nama_pegawai', models.CharField(db_index=True, max_length=255, verbose_name='Nama Pegawai')),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempat Lahir')),
                ('tanggal_lahir', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tanggal Lahir')),
                ('jenis_kelamin', models.IntegerField(blank=True, null=True, verbose_name='Jenis Kelamin')),
                ('alamat_rumah', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('no_hp', models.CharField(blank=True, max_length=50, null=True, verbose_name='No HP')),
                ('id_jabatan', models.BigIntegerField(blank=True, null=True, verbose_name='ID Jabatan')),
                ('nama_jabatan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Jabatan')),
                ('masa_kerja_jabatan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Masa Kerja Jabatan')),
                ('kode_eselon', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Kode Eselon')),
                ('id_opd', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID OPD')),
                ('nm_opd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama OPD')),
                ('id_opd_urut', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Urutan OPD (A_12)')),
                ('is_opd_induk', models.BooleanField(db_index=True, default=False, verbose_name='Is OPD Induk')),
                ('id_sub_opd', models.BigIntegerField(blank=True, null=True, verbose_name='ID Sub OPD')),
                ('nm_sub_opd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Sub OPD')),
                ('id_golongan', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID Golongan')),
                ('nama_golongan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Golongan')),
                ('nama_pangkat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Pangkat')),
                ('kategori_pegawai', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Kategori Pegawai (1=CPNS, 2=PNS, 3=P3K)')),
                ('nama_kategori_pegawai', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Kategori Pegawai')),
                ('tmt_cpns', models.CharField(blank=True, max_length=50, null=True, verbose_name='TMT CPNS')),
                ('masa_kerja_tahun', models.IntegerField(blank=True, null=True, verbose_name='Masa Kerja (Tahun)')),
                ('masa_kerja_bulan', models.IntegerField(blank=True, null=True, verbose_name='Masa Kerja (Bulan)')),
                ('akhir_kerja_p3k', models.CharField(blank=True, max_length=50, null=True, verbose_name='Akhir Kerja P3K')),
                ('raw_data', models.JSONField(help_text='Full JSON response dari ESIMPEG API', verbose_name='Raw Data dari API')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Sync')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('synced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Di-sync oleh')),
            ],
            options={
                'verbose_name': 'Data Pegawai ESIMPEG',
                'verbose_name_plural': 'Data Pegawai ESIMPEG',
                'db_table': 'api_simpeg_pegawai',
                'ordering': ['nama_pegawai'],
                'indexes': [models.Index(fields=['nip_baru'], name='api_simpeg__nip_bar_0c4c6f_idx'), models.Index(fields=['id_pegawai'], name='api_simpeg__id_pega_c276a1_idx'), models.Index(fields=['id_opd'], name='api_simpeg__id_opd_26237e_idx'), models.Index(fields=['nama_pegawai'], name='api_simpeg__nama_pe_eaa7a3_idx'), models.Index(fields=['synced_at'], name='api_simpeg__synced__2e7a48_idx'), models.Index(fields=['kode_eselon'], name='api_simpeg__kode_es_bc47d7_idx'), models.Index(fields=['id_golongan'], name='api_simpeg__id_golo_ab320a_idx'), models.Index(fields=['id_opd_urut'], name='api_simpeg__id_opd__e0e23e_idx'), models.Index(fields=['is_opd_induk'], name='api_simpeg__is_opd__86bcf1_idx'), models.Index(fields=['kategori_pegawai'], name='api_simpeg__kategor_81ac7a_idx')],
            },
        ),
    ]
