# Generated by Django 5.2.7 on 2026-07-03 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_simpeg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bupati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bupati', models.BigIntegerField(db_index=True, unique=True, verbose_name='ID Bupati')),
                ('nama', models.CharField(max_length=255, verbose_name='Nama')),
                ('gelar_depan', models.CharField(blank=True, max_length=50, null=True)),
                ('gelar_belakang', models.CharField(blank=True, max_length=100, null=True)),
                ('nik', models.CharField(blank=True, max_length=16, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('jabatan', models.IntegerField(blank=True, null=True, verbose_name='Jabatan (1=Bupati, 2=Wakil)')),
                ('nama_jabatan', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.PositiveSmallIntegerField(default=1, verbose_name='Status (1=Aktif, 0=Non Aktif)')),
                ('nama_status', models.CharField(blank=True, max_length=50, null=True)),
                ('jenis_penugasan', models.CharField(blank=True, max_length=255, null=True)),
                ('periode_awal', models.DateField(blank=True, null=True)),
                ('periode_akhir', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Raw Data dari API')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Sync')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('synced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Di-sync oleh')),
            ],
            options={
                'verbose_name': 'Bupati / Wakil Bupati',
                'verbose_name_plural': 'Bupati / Wakil Bupati',
                'db_table': 'api_simpeg_bupati',
                'ordering': ['-status', 'jabatan', 'nama'],
            },
        ),
    ]
