# Generated by Django 5.2.7 on 2026-08-20 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_simpeg', '0003_add_pas_foto_pegawai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_opd', models.BigIntegerField(db_index=True, unique=True, verbose_name='ID OPD')),
                ('nm_opd', models.CharField(db_index=True, max_length=255, verbose_name='Nama OPD')),
                ('id_opd_urut', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Urutan OPD')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='Level Hierarki')),
                ('is_opd_induk', models.BooleanField(db_index=True, default=False, verbose_name='Is OPD Induk')),
                ('status', models.IntegerField(db_index=True, default=1, verbose_name='Status (1=Aktif, 0=Non Aktif)')),
                ('id_jenis_organisasi', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID Jenis Organisasi')),
                ('nama_jenis_organisasi', models.CharField(blank=True, max_length=191, null=True, verbose_name='Nama Jenis Organisasi')),
                ('path', models.JSONField(blank=True, default=list, help_text='[{id_opd, nama}, ...] dari root', verbose_name='Path Hierarki')),
                ('raw_data', models.JSONField(verbose_name='Raw Data dari API')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Sync')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api_simpeg.unitkerja', verbose_name='Parent OPD')),
                ('synced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Di-sync oleh')),
            ],
            options={
                'verbose_name': 'Unit Kerja ESIMPEG',
                'verbose_name_plural': 'Unit Kerja ESIMPEG',
                'db_table': 'api_simpeg_unit_kerja',
                'ordering': ['id_opd_urut', 'nm_opd', 'id_opd'],
                'indexes': [models.Index(fields=['id_opd'], name='api_simpeg__id_opd_832a36_idx'), models.Index(fields=['parent'], name='api_simpeg__parent__568dc7_idx'), models.Index(fields=['id_opd_urut'], name='api_simpeg__id_opd__4e9954_idx'), models.Index(fields=['is_opd_induk'], name='api_simpeg__is_opd__ba9e19_idx'), models.Index(fields=['status'], name='api_simpeg__status_9998b0_idx')],
            },
        ),
    ]
