# Generated by Django 5.2.7 on 2026-08-24 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_simpeg', '0004_unitkerja'),
        ('idp', '0017_namakegiatanprogram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesainPembelajaranUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.TextField(blank=True, default='', help_text='Catatan tambahan desain pembelajaran unit kerja', verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diubah')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desain_unit_dibuat', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat oleh')),
                ('kompetensi_teknis', models.ForeignKey(blank=True, help_text='Kompetensi teknis utama unit kerja ini (hanya satu)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desain_unit_kerja', to='idp.namakompetensi', verbose_name='Kompetensi Teknis')),
                ('unit_kerja', models.OneToOneField(help_text='Unit kerja pemilik desain pembelajaran ini', on_delete=django.db.models.deletion.CASCADE, related_name='desain_pembelajaran', to='api_simpeg.unitkerja', verbose_name='Unit Kerja')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desain_unit_diubah', to=settings.AUTH_USER_MODEL, verbose_name='Diubah oleh')),
            ],
            options={
                'verbose_name': 'Desain Pembelajaran Unit Kerja',
                'verbose_name_plural': 'Desain Pembelajaran Unit Kerja',
                'db_table': 'api_simpeg_desain_pembelajaran_unit',
            },
        ),
        migrations.CreateModel(
            name='TujuanPembelajaranUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uraian', models.TextField(verbose_name='Uraian Tujuan Pembelajaran')),
                ('urutan', models.PositiveIntegerField(default=1, verbose_name='Urutan')),
                ('desain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tujuan', to='api_simpeg.desainpembelajaranunit', verbose_name='Desain Pembelajaran')),
            ],
            options={
                'verbose_name': 'Tujuan Pembelajaran Unit Kerja',
                'verbose_name_plural': 'Tujuan Pembelajaran Unit Kerja',
                'db_table': 'api_simpeg_tujuan_pembelajaran_unit',
                'ordering': ['urutan', 'id'],
            },
        ),
    ]
