# Generated by Django 5.2.7 on 2026-08-24 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_simpeg', '0005_desainpembelajaranunit_tujuanpembelajaranunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desainpembelajaranunit',
            name='kompetensi_teknis',
        ),
        migrations.CreateModel(
            name='KompetensiTeknisUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uraian', models.TextField(verbose_name='Uraian Kompetensi Teknis')),
                ('urutan', models.PositiveIntegerField(default=1, verbose_name='Urutan')),
                ('desain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kompetensi_teknis', to='api_simpeg.desainpembelajaranunit', verbose_name='Desain Pembelajaran')),
            ],
            options={
                'verbose_name': 'Kompetensi Teknis Unit Kerja',
                'verbose_name_plural': 'Kompetensi Teknis Unit Kerja',
                'db_table': 'api_simpeg_kompetensi_teknis_unit',
                'ordering': ['urutan', 'id'],
            },
        ),
    ]
