# Generated by Django 5.2.7 on 2026-08-27 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_simpeg', '0007_tujuan_nested_ke_kompetensi'),
    ]

    operations = [
        migrations.AddField(
            model_name='desainpembelajaranunit',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Waktu desain diarsipkan menjadi riwayat', null=True, verbose_name='Diarsipkan Pada'),
        ),
        migrations.AddField(
            model_name='desainpembelajaranunit',
            name='is_riwayat',
            field=models.BooleanField(default=False, help_text='True bila unit kerja pemilik sudah dihapus dan desain diarsipkan sebagai riwayat', verbose_name='Status Riwayat'),
        ),
        migrations.AddField(
            model_name='desainpembelajaranunit',
            name='unit_kerja_id_opd',
            field=models.BigIntegerField(blank=True, help_text='ID OPD saat desain diarsipkan menjadi riwayat', null=True, verbose_name='ID OPD (Snapshot)'),
        ),
        migrations.AddField(
            model_name='desainpembelajaranunit',
            name='unit_kerja_nm_opd',
            field=models.CharField(blank=True, default='', help_text='Nama OPD saat desain diarsipkan menjadi riwayat', max_length=255, verbose_name='Nama OPD (Snapshot)'),
        ),
        migrations.AlterField(
            model_name='desainpembelajaranunit',
            name='unit_kerja',
            field=models.OneToOneField(blank=True, help_text='Unit kerja pemilik desain pembelajaran ini (kosong bila sudah diarsipkan sebagai riwayat)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desain_pembelajaran', to='api_simpeg.unitkerja', verbose_name='Unit Kerja'),
        ),
    ]
