# Generated by Django 5.2.7 on 2026-05-07 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('article', 'Artikel'), ('video', 'Video'), ('document', 'Dokumen'), ('link', 'Link')], default='article', max_length=20, verbose_name='Tipe Konten'),
        ),
        migrations.AddField(
            model_name='article',
            name='external_url',
            field=models.URLField(blank=True, help_text='Link ke website eksternal', max_length=500, null=True, verbose_name='Link Eksternal'),
        ),
        migrations.AddField(
            model_name='article',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='Ukuran file dalam bytes', null=True, verbose_name='Ukuran File (bytes)'),
        ),
        migrations.AddField(
            model_name='article',
            name='file_type',
            field=models.CharField(blank=True, help_text='Tipe file (PDF, DOC, PPT, dll)', max_length=50, null=True, verbose_name='Tipe File'),
        ),
        migrations.AddField(
            model_name='article',
            name='file_upload',
            field=models.FileField(blank=True, help_text='Upload file langsung (PDF, DOC, PPT, dll)', null=True, upload_to='knowledge/files/%Y/%m/', verbose_name='Upload File'),
        ),
        migrations.AddField(
            model_name='article',
            name='file_url',
            field=models.URLField(blank=True, help_text='Link ke file eksternal (Google Drive, Dropbox, dll)', max_length=500, null=True, verbose_name='Link File'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Gambar thumbnail untuk artikel (recommended: 800x600px)', null=True, upload_to='knowledge/thumbnails/%Y/%m/', verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='article',
            name='video_duration',
            field=models.CharField(blank=True, help_text='Durasi video (contoh: 10:30)', max_length=20, null=True, verbose_name='Durasi Video'),
        ),
        migrations.AddField(
            model_name='article',
            name='youtube_embed_id',
            field=models.CharField(blank=True, help_text='ID video YouTube (auto-extracted dari URL)', max_length=50, null=True, verbose_name='YouTube Video ID'),
        ),
        migrations.AddField(
            model_name='article',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Link video YouTube (contoh: https://www.youtube.com/watch?v=xxxxx)', max_length=500, null=True, verbose_name='Link YouTube'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['content_type'], name='knowledge_a_content_03d887_idx'),
        ),
    ]
