# Generated by Django 5.2.7 on 2026-05-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_approval_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='approvalhistory',
            new_name='knowledge_a_article_41f7ba_idx',
            old_name='knowledge_a_article_action_idx',
        ),
        migrations.RenameIndex(
            model_name='approvalhistory',
            new_name='knowledge_a_created_d6c237_idx',
            old_name='knowledge_a_created_history_idx',
        ),
        migrations.RenameIndex(
            model_name='articlelike',
            new_name='knowledge_a_article_559477_idx',
            old_name='knowledge_a_article_like_idx',
        ),
        migrations.RenameIndex(
            model_name='articlelike',
            new_name='knowledge_a_is_like_e66713_idx',
            old_name='knowledge_a_is_like_idx',
        ),
        migrations.RenameIndex(
            model_name='articleview',
            new_name='knowledge_a_article_8ed9ba_idx',
            old_name='knowledge_a_article_idx',
        ),
        migrations.RenameIndex(
            model_name='articleview',
            new_name='knowledge_a_viewed__d2a453_idx',
            old_name='knowledge_a_viewed__idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='knowledge_c_article_df36f6_idx',
            old_name='knowledge_c_article_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='knowledge_c_user_id_ebfe36_idx',
            old_name='knowledge_c_user_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='knowledge_c_created_d339f7_idx',
            old_name='knowledge_c_created_idx',
        ),
        migrations.RenameIndex(
            model_name='commentlike',
            new_name='knowledge_c_comment_f599b9_idx',
            old_name='knowledge_c_comment_user_idx',
        ),
        migrations.RenameIndex(
            model_name='commentlike',
            new_name='knowledge_c_is_like_9001f1_idx',
            old_name='knowledge_c_is_like_idx',
        ),
    ]
