# Generated by Django 5.2.7 on 2026-05-25 09:44

import apps.knowledge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_tag_color_tag_description_tag_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file_upload',
            field=models.FileField(blank=True, help_text='Upload file langsung (PDF, DOC, PPT, dll)', null=True, upload_to=apps.knowledge.models.knowledge_file_upload_to, verbose_name='Upload File'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Gambar thumbnail untuk artikel (recommended: 800x600px)', null=True, upload_to=apps.knowledge.models.knowledge_thumbnail_upload_to, verbose_name='Thumbnail'),
        ),
    ]
