# Generated by Django 5.2.7 on 2026-08-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0016_article_source_course_one_to_one'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='articledocument',
            new_name='knowledge_a_article_16cf0d_idx',
            old_name='knowledge_articledoc_article_idx',
        ),
        migrations.RenameIndex(
            model_name='articledocument',
            new_name='knowledge_a_source__03dcf7_idx',
            old_name='knowledge_articledoc_lesson_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='sync_thumbnail',
            field=models.BooleanField(default=True, help_text='Jika True, thumbnail artikel akan mengikuti thumbnail course LMS (mirror). Jika user mengubah/menghapus thumbnail secara manual di KMS, field ini otomatis False agar tidak ditimpa oleh sinkronisasi.', verbose_name='Sinkron thumbnail dari Course LMS'),
        ),
    ]
