# Generated by Django 5.2.7 on 2025-10-27 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(help_text='Nama lengkap user (match Laravel)', max_length=191, verbose_name='name')),
                ('email', models.EmailField(help_text='Email user (unique, match Laravel)', max_length=191, unique=True, verbose_name='email')),
                ('username', models.CharField(help_text='Username untuk login (bisa berisi email, NIP, atau custom username)', max_length=150, unique=True, verbose_name='username')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_pegawai', models.IntegerField(blank=True, help_text='FK ke ms_pegawai (match Laravel)', null=True)),
                ('user_id_opd', models.IntegerField(blank=True, help_text='ID OPD user (nullable)', null=True)),
                ('image', models.CharField(default='', help_text='Path to profile image', max_length=150)),
                ('id_status', models.IntegerField(default=1, help_text='1=Active, 0=Inactive')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
    ]
