# Generated by Django 5.2.7 on 2025-10-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Email user (unique, nullable, match Laravel)', max_length=191, null=True, unique=True, verbose_name='email'),
        ),
    ]
