# Generated by Django 5.2.7 on 2026-05-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_id_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_esimpeg_user',
            field=models.BooleanField(default=False, help_text='User created from ESIMPEG fallback authentication', verbose_name='ESIMPEG User'),
        ),
        migrations.AddField(
            model_name='user',
            name='nip',
            field=models.CharField(blank=True, help_text='Nomor Induk Pegawai (18 digit)', max_length=18, null=True, unique=True, verbose_name='NIP'),
        ),
    ]
