# Generated by Django 5.2.7 on 2026-05-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_esimpeg_user_user_nip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nip',
        ),
    ]
