# Generated by Django 5.2.7 on 2026-05-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_nip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_esimpeg_user',
        ),
    ]
