# Generated by Django 5.2.7 on 2026-07-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile'),
        ('referensi', '0005_mskategoriuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kategori_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referensi.mskategoriuser', verbose_name='Kategori User'),
        ),
    ]
