# Generated by Django 5.2.7 on 2026-07-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_kategori_user'),
        ('referensi', '0005_mskategoriuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instansi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referensi.msinstansi', verbose_name='Instansi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True, verbose_name='Jenis Kelamin'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kabupaten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referensi.mskabupaten', verbose_name='Kabupaten/Kota'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kecamatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referensi.mskecamatan', verbose_name='Kecamatan'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kelurahan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referensi.mskelurahan', verbose_name='Kelurahan/Desa'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perguruan_tinggi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referensi.msperguruantinggi', verbose_name='Perguruan Tinggi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='program_studi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referensi.msprogramstudi', verbose_name='Program Studi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='provinsi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referensi.msprovinsi', verbose_name='Provinsi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempat Lahir'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='alamat_domisili',
            field=models.TextField(blank=True, null=True, verbose_name='Detail Alamat Domisili'),
        ),
    ]
