# Generated by Django 5.2.7 on 2026-06-09 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, null=True, verbose_name='Ringkasan')),
                ('content', models.TextField(verbose_name='Konten')),
                ('category', models.CharField(choices=[('Program', 'Program'), ('Kerjasama', 'Kerjasama'), ('Event', 'Event'), ('Pengumuman', 'Pengumuman')], default='Program', max_length=50, verbose_name='Kategori')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='news/thumbnails/%Y/%m/', verbose_name='Thumbnail')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Status')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Dilihat')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Dipublikasikan Pada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to=settings.AUTH_USER_MODEL, verbose_name='Penulis')),
            ],
            options={
                'verbose_name': 'Berita',
                'verbose_name_plural': 'Berita',
                'db_table': 'news',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='news_slug_fb3ac9_idx'), models.Index(fields=['status'], name='news_status_66f3e7_idx'), models.Index(fields=['category'], name='news_categor_afc81a_idx'), models.Index(fields=['published_at'], name='news_publish_b01c8c_idx')],
            },
        ),
    ]
