# Generated by Django 5.2.7 on 2026-05-07 14:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('password_hash', models.CharField(help_text='Password hash (Django format)', max_length=255)),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('changed_by', models.CharField(help_text='User yang ganti password', max_length=150)),
                ('is_synced', models.BooleanField(db_index=True, default=False, help_text='Sudah di-sync ke aplikasi lain?')),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_attempts', models.IntegerField(default=0)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Password Change Event',
                'verbose_name_plural': 'Password Change Events',
                'db_table': 'password_change_events',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['username', 'is_synced'], name='password_ch_usernam_8c4ea4_idx'), models.Index(fields=['changed_at'], name='password_ch_changed_a6b609_idx'), models.Index(fields=['is_synced', 'changed_at'], name='password_ch_is_sync_45efa2_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(help_text='Nama aplikasi (contoh: esimpeg)', max_length=100, unique=True)),
                ('webhook_url', models.URLField(help_text='URL endpoint untuk terima webhook')),
                ('secret_key', models.CharField(help_text='Secret key untuk validasi webhook', max_length=255)),
                ('event_type', models.CharField(choices=[('password_changed', 'Password Changed'), ('user_disabled', 'User Disabled'), ('user_enabled', 'User Enabled'), ('permission_changed', 'Permission Changed')], default='password_changed', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_sent', models.IntegerField(default=0, help_text='Total webhook sent')),
                ('total_success', models.IntegerField(default=0, help_text='Total success')),
                ('total_failed', models.IntegerField(default=0, help_text='Total failed')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook Registration',
                'verbose_name_plural': 'Webhook Registrations',
                'db_table': 'webhook_registrations',
                'indexes': [models.Index(fields=['app_name'], name='webhook_reg_app_nam_f77512_idx'), models.Index(fields=['event_type', 'is_active'], name='webhook_reg_event_t_0e4e69_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(help_text='Webhook payload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='integrations.passwordchangeevent')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.webhookregistration')),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'db_table': 'webhook_logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['status', 'sent_at'], name='webhook_log_status_bda710_idx'), models.Index(fields=['registration', 'status'], name='webhook_log_registr_04f6d9_idx')],
            },
        ),
    ]
