# Generated by Django 5.2.7 on 2025-10-24 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kontrol', models.CharField(max_length=100, unique=True)),
                ('label_kontrol', models.CharField(max_length=100)),
                ('deskripsi_kontrol', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission Control',
                'verbose_name_plural': 'Permission Controls',
                'db_table': 'permission_controls',
                'ordering': ['nama_kontrol'],
            },
        ),
        migrations.CreateModel(
            name='PermissionFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_fungsi', models.CharField(max_length=100, unique=True)),
                ('label_fungsi', models.CharField(max_length=100)),
                ('deskripsi_fungsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission Function',
                'verbose_name_plural': 'Permission Functions',
                'db_table': 'permission_functions',
                'ordering': ['nama_fungsi'],
            },
        ),
        migrations.CreateModel(
            name='PermissionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_module', models.CharField(max_length=100, unique=True)),
                ('label_module', models.CharField(max_length=100)),
                ('deskripsi_module', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='fas fa-folder', help_text='FontAwesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Order in sidebar')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission Module',
                'verbose_name_plural': 'Permission Modules',
                'db_table': 'permission_modules',
                'ordering': ['order', 'nama_module'],
            },
        ),
        migrations.CreateModel(
            name='PermissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='manajemen_aplikasi.permissioncontrol')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='manajemen_aplikasi.permissionfunction')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='manajemen_aplikasi.permissionmodule')),
            ],
            options={
                'verbose_name': 'Permission Rule',
                'verbose_name_plural': 'Permission Rules',
                'db_table': 'permission_rules',
                'ordering': ['module__order', 'control__nama_kontrol', 'function__nama_fungsi'],
                'unique_together': {('module', 'control', 'function')},
            },
        ),
        migrations.CreateModel(
            name='RoleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_rules', to='auth.group')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='manajemen_aplikasi.permissionrule')),
            ],
            options={
                'verbose_name': 'Role Rule',
                'verbose_name_plural': 'Role Rules',
                'db_table': 'role_rules',
                'ordering': ['role__name', 'rule__module__order'],
                'unique_together': {('role', 'rule')},
            },
        ),
    ]
