# Generated by Django 5.2.7 on 2025-11-07 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_aplikasi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTableSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(help_text='Unique identifier for the page/table (e.g., user_list, role_list)', max_length=100)),
                ('selected_ids', models.JSONField(default=list, help_text='List of selected item IDs')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Table Selection',
                'verbose_name_plural': 'User Table Selections',
                'db_table': 'user_table_selections',
                'indexes': [models.Index(fields=['user', 'page_key'], name='user_table__user_id_73bc0f_idx')],
                'unique_together': {('user', 'page_key')},
            },
        ),
    ]
