# Generated by Django 5.2.7 on 2025-11-20 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_aplikasi', '0002_usertableselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('permission_key', models.CharField(blank=True, max_length=150, null=True)),
                ('url_name', models.CharField(blank=True, max_length=150, null=True)),
                ('external_url', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(default='fas fa-folder', max_length=50)),
                ('type', models.CharField(default='module', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('category', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='manajemen_aplikasi.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'db_table': 'menu_items',
                'ordering': ['category', 'parent_id', 'order', 'name'],
            },
        ),
    ]
