# Generated by Django 5.2.7 on 2026-01-13 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_aplikasi', '0004_menucategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrule',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='manajemen_aplikasi.permissioncontrol'),
        ),
        migrations.AlterField(
            model_name='permissionrule',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='manajemen_aplikasi.permissionfunction'),
        ),
        migrations.AlterField(
            model_name='permissionrule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='manajemen_aplikasi.permissionmodule'),
        ),
        migrations.AlterField(
            model_name='rolerule',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='manajemen_aplikasi.permissionrule'),
        ),
    ]
