# Generated by Django 5.2.7 on 2026-02-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_aplikasi', '0005_alter_permissionrule_control_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(max_length=191)),
                ('url', models.CharField(max_length=191)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Documentation',
                'verbose_name_plural': 'API Documentation',
                'db_table': 'api_documentation',
                'ordering': ['-id'],
                'unique_together': {('method_type', 'url')},
            },
        ),
        migrations.AddIndex(
            model_name='apidocumentation',
            index=models.Index(fields=['url'], name='api_doc_url_idx'),
        ),
        migrations.AddIndex(
            model_name='apidocumentation',
            index=models.Index(fields=['method_type'], name='api_doc_method_idx'),
        ),
        migrations.AddIndex(
            model_name='apidocumentation',
            index=models.Index(fields=['is_active'], name='api_doc_active_idx'),
        ),
    ]
