# Generated by Django 5.2.7 on 2026-02-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_aplikasi', '0006_apidocumentation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apidocumentation',
            new_name='api_documen_url_b0782d_idx',
            old_name='api_doc_url_idx',
        ),
        migrations.RenameIndex(
            model_name='apidocumentation',
            new_name='api_documen_method__c36e3c_idx',
            old_name='api_doc_method_idx',
        ),
        migrations.RenameIndex(
            model_name='apidocumentation',
            new_name='api_documen_is_acti_8df1ab_idx',
            old_name='api_doc_active_idx',
        ),
    ]
