# Generated by Django 5.2.7 on 2026-03-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_aplikasi', '0007_rename_api_doc_url_idx_api_documen_url_b0782d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboBoxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Combo Box Config',
                'verbose_name_plural': 'Combo Box Configs',
                'db_table': 'combo_box_configs',
                'ordering': ['code'],
            },
        ),
    ]
