# Generated by Django 5.2.7 on 2026-05-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manajemen_aplikasi', '0008_comboboxconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Setting key (e.g., app_name, contact_email)', max_length=191, unique=True)),
                ('value', models.TextField(blank=True, help_text='Setting value', null=True)),
                ('type', models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON'), ('file', 'File'), ('url', 'URL'), ('email', 'Email')], default='string', help_text='Data type of the value', max_length=191)),
                ('category', models.CharField(choices=[('general', 'General'), ('contact', 'Contact'), ('social', 'Social Media'), ('appearance', 'Appearance'), ('system', 'System')], default='general', help_text='Setting category', max_length=191)),
                ('description', models.TextField(blank=True, help_text='Description of this setting', null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether this setting is accessible via public API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Setting',
                'verbose_name_plural': 'App Settings',
                'db_table': 'app_settings',
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['key'], name='app_setting_key_460547_idx'), models.Index(fields=['category'], name='app_setting_categor_1bb2cf_idx'), models.Index(fields=['is_public'], name='app_setting_is_publ_b7d492_idx')],
            },
        ),
    ]
