# Generated by Django 5.2.7 on 2026-07-01 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('manajemen_aplikasi', '0010_menuitem_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_url', models.CharField(blank=True, default='/admin/dashboard', help_text='Redirect URL when this role is selected at login', max_length=255)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group')),
            ],
            options={
                'verbose_name': 'Role Profile',
                'verbose_name_plural': 'Role Profiles',
                'db_table': 'group_profiles',
            },
        ),
    ]
