# Generated by Django 5.2.7 on 2025-11-03 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('endpoint', models.CharField(db_index=True, max_length=500)),
                ('full_url', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('ip_address', models.CharField(db_index=True, max_length=45)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('query_params', models.JSONField(blank=True, null=True)),
                ('status_code', models.SmallIntegerField(db_index=True)),
                ('response_size', models.IntegerField(blank=True, null=True)),
                ('response_time', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('api_version', models.CharField(blank=True, max_length=10, null=True)),
                ('rate_limit_hit', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_access_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['method', 'endpoint'], name='api_access__method_0f918b_idx'), models.Index(fields=['user', 'created_at'], name='api_access__user_id_79a921_idx')],
            },
        ),
    ]
