# Generated by Django 5.2.7 on 2025-11-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apiaccesslog',
            new_name='ms_log_api_method_878072_idx',
            old_name='api_access__method_0f918b_idx',
        ),
        migrations.RenameIndex(
            model_name='apiaccesslog',
            new_name='ms_log_api_user_id_91e99a_idx',
            old_name='api_access__user_id_79a921_idx',
        ),
        migrations.AlterModelTable(
            name='apiaccesslog',
            table='ms_log_api',
        ),
    ]
