# Generated by Django 5.2.7 on 2025-11-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_table_to_ms_log_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsLogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=191)),
                ('table_name', models.CharField(db_index=True, max_length=191)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ms_log_data',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='ms_log_data_user_id_f24e30_idx'), models.Index(fields=['action', 'table_name'], name='ms_log_data_action_1025af_idx')],
            },
        ),
    ]
