# Generated by Django 5.2.7 on 2025-11-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_ms_log_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='mslogdata',
            name='description',
            field=models.CharField(blank=True, help_text='Additional description', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mslogdata',
            name='username',
            field=models.CharField(blank=True, help_text='Username for quick reference', max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='mslogdata',
            name='via',
            field=models.CharField(blank=True, db_index=True, help_text='web, api_v4, api_v5', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mslogdata',
            name='action',
            field=models.CharField(db_index=True, help_text='login, logout, create, update, delete', max_length=191),
        ),
        migrations.AlterField(
            model_name='mslogdata',
            name='ip_address',
            field=models.CharField(blank=True, db_index=True, help_text='Client IP address', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='mslogdata',
            name='new_data',
            field=models.JSONField(blank=True, help_text='Data after change (for create/update)', null=True),
        ),
        migrations.AlterField(
            model_name='mslogdata',
            name='old_data',
            field=models.JSONField(blank=True, help_text='Data before change (for update/delete)', null=True),
        ),
        migrations.AlterField(
            model_name='mslogdata',
            name='record_id',
            field=models.IntegerField(blank=True, help_text='ID of affected record', null=True),
        ),
        migrations.AlterField(
            model_name='mslogdata',
            name='table_name',
            field=models.CharField(db_index=True, help_text='Target table (users, pegawai, etc)', max_length=191),
        ),
        migrations.AlterField(
            model_name='mslogdata',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser/client user agent', null=True),
        ),
        migrations.AlterField(
            model_name='mslogdata',
            name='user_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='User who performed action', null=True),
        ),
        migrations.AddIndex(
            model_name='mslogdata',
            index=models.Index(fields=['via', 'created_at'], name='ms_log_data_via_f9a1ef_idx'),
        ),
    ]
