# Generated by Django 5.2.7 on 2026-06-03 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_hybrid_fields_to_ms_log_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('course_completed', 'Kursus Selesai'), ('essay_graded', 'Esai Dinilai'), ('certificate_issued', 'Sertifikat Diterbitkan')], max_length=50, verbose_name='Tipe')),
                ('title', models.CharField(max_length=255, verbose_name='Judul')),
                ('message', models.TextField(blank=True, verbose_name='Pesan')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Tautan')),
                ('is_read', models.BooleanField(default=False, verbose_name='Dibaca')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'db_table': 'core_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_ca0f65_idx'), models.Index(fields=['is_read'], name='core_notifi_is_read_969c62_idx')],
            },
        ),
    ]
