# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mslogdata',
            name='diskripsi_tabel',
            field=models.CharField(blank=True, help_text='Deskripsi tabel', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mslogdata',
            name='created_byname',
            field=models.CharField(blank=True, help_text='User display name (created by)', max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='mslogdata',
            name='created_error',
            field=models.TextField(blank=True, help_text='Error message if any', null=True),
        ),
        migrations.AddField(
            model_name='mslogdata',
            name='updated_by',
            field=models.IntegerField(blank=True, help_text='User who last updated', null=True),
        ),
        migrations.AddField(
            model_name='mslogdata',
            name='updated_byname',
            field=models.CharField(blank=True, help_text='User display name (updated by)', max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='mslogdata',
            name='updated_ip',
            field=models.CharField(blank=True, help_text='Last update IP', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='mslogdata',
            name='updated_user_agent',
            field=models.TextField(blank=True, help_text='Last update user agent', null=True),
        ),
        migrations.AddField(
            model_name='mslogdata',
            name='updated_data',
            field=models.JSONField(blank=True, help_text='Data after last update', null=True),
        ),
        migrations.AddField(
            model_name='mslogdata',
            name='updated_error',
            field=models.TextField(blank=True, help_text='Error on last update', null=True),
        ),
        migrations.AddField(
            model_name='mslogdata',
            name='status_log',
            field=models.IntegerField(blank=True, help_text='Status log (1=active, 0=deleted)', null=True),
        ),
        migrations.AddField(
            model_name='mslogdata',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True),
        ),
    ]
